// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqycespdqmszyvkeqbje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxeWNlc3BkcW1zenl2a2VxYmplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTU4ODEsImV4cCI6MjA2OTc3MTg4MX0.-FCKUx3Q45lrRlxoBcCgLEkoWwGCPKb5n-0Mvuee9V4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});